# Generated by Django 5.0 on 2026-03-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipejournal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time',
            new_name='cook_time',
        ),
    ]
