# Generated by Django 5.0 on 2026-04-07 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipejournal', '0002_rename_time_recipe_cook_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionsstep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='myrecipejournal.recipe'),
        ),
    ]
