# Generated by Django 5.0 on 2026-04-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipejournal', '0003_alter_instructionsstep_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(default=0, help_text='e.g., 2 cups, 1 tbsp', max_length=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='grams', help_text='e.g.grams, kg, lbs,cups,tsp, tbsp', max_length=10),
        ),
    ]
