# Generated by Django 5.0 on 2026-04-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipejournal', '0004_remove_ingredient_measurement_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
