# Generated by Django 5.2.16 on 2026-08-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipejournal', '0007_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('ml', 'Millilitres'), ('l', 'Litre'), ('g', 'Grams'), ('kg', 'Kilograms'), ('mg', 'Milligrams'), ('lb', 'Pounds'), ('oz', 'Ounces'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('pc', 'Pieces'), ('pkt', 'Packets'), ('btl', 'Bottles'), ('can', 'Cans'), ('pinch', 'Pinch'), ('dash', 'Dash'), ('clove', 'Clove'), ('slice', 'Slice')], max_length=12),
        ),
    ]
