# Generated by Django 5.2.16 on 2026-08-26 05:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipejournal', '0008_alter_ingredient_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('', 'Select unit...'), ('tsp', 'Teaspoons'), ('tbsp', 'Tablespoons'), ('cup', 'Cups'), ('ml', 'Millilitres'), ('l', 'Litre'), ('g', 'Grams'), ('kg', 'Kilograms'), ('mg', 'Milligrams'), ('lb', 'Pounds'), ('oz', 'Ounces'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('pc', 'Pieces'), ('pkt', 'Packets'), ('btl', 'Bottles'), ('can', 'Cans'), ('pinch', 'Pinch'), ('dash', 'Dash'), ('clove', 'Clove'), ('slice', 'Slice')], default='', max_length=12),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_photos/')),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph', models.TextField(max_length=500)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='myrecipejournal.profile')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='myrecipejournal.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='myrecipejournal.profile')),
            ],
        ),
    ]
